# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_four',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
