# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funt', '0003_auto_20160825_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
